export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const TOGGLE_CART_VISIBILITY = "TOGGLE_CART_VISIBILITY";
export const ADD_COLLECTION_ITEM = "ADD_COLLECTION_ITEM";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
export const REMOVE_COLLECTION_ITEM = "REMOVE_COLLECTION_ITEM";
export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";
